### ISSUE TITLE
.env variable not being found in Netlify

### ISSUE THREAD

**Issue by KubukaH** [fauna-labs/fauna-streams-with-react#2]
I cloned this repo, setup the environment as described and pushed it to Netlify. I tried to save just one transaction but was met with this error, `Unauthorized: unauthorized. Check that endpoint, schema, port and secret are correct during client’s instantiation`. After looking around I discovered that the problem is I don't understand how the `.env` file shares it's data to the `./db/operations.js` file. When I put the SECRET Key directly in the `operations.js` it works properly, but when I put it in the `.env` file it does not work. Furthermore, when I put the KEY in NETLIFY's `environment` I get the `Unauthorized ...` error.

I cloned this repo and tested it in my own repo also, they behave just the same. Netlify could not be sharing it's `.env` to `Fauna`. Is there a way to set environment variables in Fauna? I tried to check the settings but I found nowhere where I can do that. I am on a free plan, perhaps it is available on paid plans, or maybe I just missed it.

Thank you for helping out.

**Comment by Shadid12** [comment]
You have to set those `env` in netlify take a look at the Netlify documentation
https://docs.netlify.com/configure-builds/environment-variables/
